finalProj/flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm, SearchForm
from ..models import User

users = Blueprint("users", __name__)

""" ************ User Management views ************ """


# TODO: implement

@users.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("spotify.query_results", query=form.search_query.data))

    return render_template("index.html", form=form)




@users.route("/register", methods=["GET", "POST"])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('users.index'))

    form = RegistrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(
                form.password.data).decode('utf-8')

            user = User(username=form.username.data,
                        email=form.email.data, password=hashed_password)
            user.save()
            return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.index'))

    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.objects(username=form.username.data).first()

            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('users.account'))
            else:
                flash("Please Authenticate Again")
    return render_template('login.html', form=form)


# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.index'))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            # TODO: handle update username form submit
            try:
                update_username_form.validate_username(update_username_form.username.data)
                
            except:
                print("stuff")
                

            newUsername = update_username_form.username.data

            current_user.username = newUsername

            current_user.save()
            
            return redirect(url_for('users.login'))

        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            # TODO: handle update profile pic form submit
            image = update_profile_pic_form.picture.data
            filename = secure_filename(image.filename)
            content_type = f'images/{filename[-3:]}'

            if current_user.profile_pic.get() is None:
                # user doesn't have a profile picture => add one
                current_user.profile_pic.put(
                    image.stream, content_type=content_type)
            else:
                # user has a profile picture => replace it
                current_user.profile_pic.replace(
                    image.stream, content_type=content_type)
            current_user.save()

            return redirect(url_for('users.account'))

    profile_pic_bytes = BytesIO(current_user.profile_pic.read())
    profile_pic_base64 = base64.b64encode(
        profile_pic_bytes.getvalue()).decode()
    # TODO: handle get requests
    return render_template('account.html', update_username_form=update_username_form, update_profile_pic_form=update_profile_pic_form, image=profile_pic_base64)

finalProj/flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if image %}
        <img class="rounded-2xl h-24 w-24" src="data:image/png;base64,{{image}}" alt="image">
    {% endif %}

    Hello, Hope you are having a good day {{current_user.username}}

</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Username
    </h3>
    <form class="review-form" method="POST" action="">
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username.label }}
            {{ update_username_form.username(class="form-content") }}
            {% if update_username_form.username.errors %}
            <div class="error" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Profile Picture
    </h3>
    <form class="review-form" method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label }}
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="error" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<div class="flex justify-center">
    <a class="review-button" href="{{ url_for('auth.connect') }}">Connect your Spotify account</a>
</div>
{% endblock %}

finalProj/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <script src="https://cdn.tailwindcss.com"></script> 
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Music Spot</title>
    {% endif %}
</head>
<body>

    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
    <script>
  document.addEventListener("DOMContentLoaded", function() {
    const themeToggle = document.getElementById("themetoggle");
    const html = document.querySelector("html");
    let darkModeEnabled = localStorage.getItem("darkModeEnabled");

    // Check if dark mode preference is stored in localStorage
    if (darkModeEnabled === "true") {
      html.classList.add("dark-mode");
    }

    themeToggle.addEventListener("click", function() {
      // Toggle dark mode class
      html.classList.toggle("dark-mode");
      // Update dark mode preference in localStorage
      darkModeEnabled = html.classList.contains("dark-mode");
      localStorage.setItem("darkModeEnabled", darkModeEnabled);
    });
  });
</script>
</body>
</html>

finalProj/flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between ">
    <a class="m-5 navlink" href="{{ url_for('users.index') }}">
        <span class="hidden sm:block">Home</span>
        <span class="block sm:hidden">Home</span>
    </a> 
  
    {% if current_user.is_authenticated %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.account') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-green-400/20 hover:!bg-green-500/50 !text-green-400 hover:!text-green-300" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register') }}">Register</a>
    </div>
    {% endif %}
</nav>
  <a  class="fixed bottom-0 right-0 mb-5 mr-5 navlink">
        <button id="themetoggle" >Toggle Theme</button>
    </a> 
{% block content %}{% endblock %}{% endblock %}

finalProj/flask_app/templates/index.html
{% extends "header.html" %} {% block content %}
<div class="main-container">
  <h2 class="main-title"> Learn About Music and Your own Music Taste  </h2>
  <form class="searchbar" action="/" method="POST">
    {{ form.csrf_token }}
    {{ form.search_query(class="form-control", placeholder="Search Relevant Tracks!") }}

    {% if form.search_query.errors %}
      <div class="error" role="alert">
        {% for error in form.search_query.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% endif %}
    
    {{ form.submit(class="form-button") }}
  </form>
</div>
{% endblock %}

finalProj/flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

finalProj/flask_app/templates/query.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

<div class=" flex flex-col justify-center items-center " >
<div class=" grid gap-11 justify-center md:grid-cols-2 lg:grid-cols-4  " >
  {% for result in results %}
  <div class = "hover:scale-110 transition-transform duration-300 ease-in-out">
    <h5 class="card-title"> 
      <a href="{{ result.url }}" target="_blank">
        <div>
            {{ result.name }}
            <img src="{{ result.image_url }}" height="200px" width="300px">
        </div>
    </a>
    </h5>
  
  </a>
  </div>
  {% endfor %}
</div>
</div>

{% endblock %}

finalProj/flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Registration</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>
<!-- Registration Form: -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="error" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="error" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>

{% endblock %}

finalProj/flask_app/templates/user_profile.html
{% extends "header.html" %}

{% block content %}
    {% if error %}
        <b class="text-red-400" role="alert">
            {{ error }}
        </b>
    {% endif %}
    <div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
        <h2 class="main-title text-4xl mb-4">Your Music Profile</h2> 
    </div>
<br><br><br><br>
    <!-- Display top 6 artists -->
    <div class="container mx-auto w-full md:w-2/3 lg:w-2/3 mb-8"> 
        <h3 class="sub-title text-center text-3xl mb-6">Top 6 Artists:</h3> 
        <div class="grid grid-cols-2 sm:grid-cols-3 gap-4">
            {% for artist in top_artists %}
                <a href="{{ artist.profile }}" target="_blank" class="text-center block relative group">
                    {% if artist.image %}
                        <img src="{{ artist.image }}" alt="{{ artist.name }} Image" class="h-64 w-full object-cover transition duration-300 ease-in-out transform group-hover:scale-105">
                    {% endif %}
                    <div class="absolute inset-0 bg-black bg-opacity-50 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
                        <span class="text-white text-lg font-bold">View Profile</span>
                    </div>
                    <span class="block mt-2">{{ artist.name }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
<br><br><br><br>
    <!-- Display top 5 tracks -->
    <div class="container mx-auto w-full mb-8">
        <h3 class="sub-title text-center text-3xl mb-6">Top 5 Tracks:</h3> 
        <div class="grid grid-cols-5 gap-4">
            {% for track in top_tracks %}
                <a href="{{ track.spotify_link }}" target="_blank" class="text-center block relative group">
                    {% if track.image %}
                        <img src="{{ track.image }}" alt="{{ track.name }} Image" class="h-64 w-full object-cover transition duration-300 ease-in-out transform group-hover:scale-105">
                    {% endif %}
                    <div class="absolute inset-0 bg-black bg-opacity-50 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
                        <span class="text-white text-lg font-bold">Listen on Spotify</span>
                    </div>
                    <span class="block mt-2">{{ track.name }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
<br><br><br><br>
    <!-- Display top 5 genres -->
    <div class="container mx-auto w-full md:w-2/3 lg:w-1/3 mb-8">
        <h3 class="sub-title text-center text-3xl mb-6">Top 5 Genres:</h3> 
        <ul class="list-disc list-inside">
            {% for genre in top_genres %}
                <li class="mb-4 text-xl">{{ genre }}</li> 
            {% endfor %}
        </ul>
    </div>
{% endblock %}


<br><br><br><br>